# Generated by Django 4.2.16 on 2024-12-09 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0002_alter_car_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='purchased_by',
            field=models.ManyToManyField(blank=True, related_name='purchased_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
